services:
  - type: web
    name: webapi
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/ESGI-4AL2/serverless-blueprint-render # optional
    region: frankfurt # optional (defaults to oregon)
    plan: free # optional (defaults to starter instance type)
    branch: main # optional (defaults to master)
    envVars:
      - key: INTERNAL_DB_URL
        fromDatabase:
          name: mydb
          property: connectionString

databases:
  - name: mydb
    databaseName: toto # optional (Render may add a suffix)
    region: frankfurt
    plan: free
